/*
 * Copyright 2026 Vaquar Khan
 * SPDX-License-Identifier: Apache-2.0
 */

package io.github.vaquarkhan.aiv.cli;

import java.io.IOException;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.EnumSet;
import java.util.HashSet;
import java.util.Set;

/**
 * Writes a starter {@code .aiv/config.yaml} and {@code .aiv/design-rules.yaml} based on rough language detection.
 *
 * @author Vaquar Khan
 */
public final class InitCommand {

    private InitCommand() {
    }

    public static int run(Path workspace) throws IOException {
        Path dotAiv = workspace.resolve(".aiv");
        Files.createDirectories(dotAiv);
        Path config = dotAiv.resolve("config.yaml");
        if (Files.exists(config)) {
            System.out.println(".aiv/config.yaml already exists - leaving it unchanged.");
            return 0;
        }

        Set<String> langs = detectLanguages(workspace);
        String yaml = buildConfigYaml(langs);
        Files.writeString(config, yaml);

        Path design = dotAiv.resolve("design-rules.yaml");
        if (!Files.exists(design)) {
            Files.writeString(design, defaultDesignRules());
            System.out.println("Wrote " + design.toAbsolutePath());
        } else {
            System.out.println("Left existing file unchanged: " + design.toAbsolutePath());
        }

        System.out.println("Wrote " + config.toAbsolutePath());
        return 0;
    }

    private static Set<String> detectLanguages(Path workspace) throws IOException {
        Set<String> found = new HashSet<>();
        Files.walkFileTree(workspace, EnumSet.noneOf(java.nio.file.FileVisitOption.class), 6,
                new SimpleFileVisitor<>() {
                    @Override
                    public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) {
                        String n = file.getFileName().toString().toLowerCase();
                        if (n.endsWith(".java")) found.add("java");
                        else if (n.endsWith(".py")) found.add("python");
                        else if (n.endsWith(".go")) found.add("go");
                        else if (n.endsWith(".rs")) found.add("rust");
                        else if (n.endsWith(".kt") || n.endsWith(".kts")) found.add("kotlin");
                        else if (n.endsWith(".js") || n.endsWith(".ts") || n.endsWith(".tsx") || n.endsWith(".jsx")) {
                            found.add("js");
                        }
                        return found.size() >= 5 ? FileVisitResult.TERMINATE : FileVisitResult.CONTINUE;
                    }

                    @Override
                    public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) {
                        String name = dir.getFileName().toString();
                        if ("target".equals(name) || "node_modules".equals(name) || ".git".equals(name)) {
                            return FileVisitResult.SKIP_SUBTREE;
                        }
                        return FileVisitResult.CONTINUE;
                    }
                });
        return found;
    }

    private static String buildConfigYaml(Set<String> langs) {
        double entropy = langs.contains("java") ? 5.0 : 3.8;
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by: java -jar aiv-cli.jar init\n");
        sb.append("# Detected signals: ").append(langs.isEmpty() ? "none (defaults)" : String.join(", ", langs)).append("\n\n");
        sb.append("fail_fast: false\n\n");
        sb.append("gates:\n");
        sb.append("  - id: density\n");
        sb.append("    enabled: true\n");
        sb.append("    config:\n");
        sb.append("      ldr_threshold: 0.25\n");
        sb.append("      entropy_threshold: ").append(entropy).append("\n");
        sb.append("      refactor_net_loc_threshold: -50\n");
        sb.append("  - id: design\n");
        sb.append("    enabled: true\n");
        sb.append("    config:\n");
        sb.append("      rules_path: .aiv/design-rules.yaml\n");
        sb.append("  - id: dependency\n");
        sb.append("    enabled: true\n");
        sb.append("  - id: invariant\n");
        sb.append("    enabled: false\n");
        sb.append("  - id: doc-integrity\n");
        sb.append("    enabled: false\n");
        sb.append("    config:\n");
        sb.append("      rules_path: .aiv/doc-rules.yaml\n");
        sb.append("      auto: true\n");
        return sb.toString();
    }

    private static String defaultDesignRules() {
        return """
                # Starter rules - tighten keywords and forbidden_calls for your codebase
                constraints:
                  - id: no-system-exit
                    keywords: []
                    forbidden_calls: [System.exit]
                    required_calls: []

                  - id: no-emoji-in-code
                    keywords: []
                    forbidden_calls: ["\\u2705", "\\u274C"]
                    required_calls: []

                  - id: no-ai-generated-markers
                    keywords: []
                    forbidden_calls: ["Generated by AI", "AI-generated", "Generated by ChatGPT"]
                    required_calls: []
                """;
    }
}
