/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.vaquarkhan.aiv.plugin.design;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

/**
 * @author Vaquar Khan
 */
class JavaDesignSurfaceTest {

    @Test
    void nullContentReturnsEmpty() {
        assertEquals("", JavaDesignSurface.lowerForRuleMatching("X.java", null));
    }

    @Test
    void nullPathUsesRawLowercase() {
        assertEquals("foo", JavaDesignSurface.lowerForRuleMatching(null, "FOO"));
    }

    @Test
    void nonJavaPathUsesRawLowercase() {
        assertEquals("hello", JavaDesignSurface.lowerForRuleMatching("x.py", "HELLO"));
    }

    @Test
    void unparseableJavaFallsBackToRawLowercase() {
        String raw = "class {";
        assertEquals(raw.toLowerCase(), JavaDesignSurface.lowerForRuleMatching("A.java", raw));
    }

    @Test
    void stripsOrdinaryStringLiterals() {
        String src = """
                class T {
                  String s = "Generated by AI";
                }
                """;
        String surface = JavaDesignSurface.lowerForRuleMatching("X.java", src);
        assertFalse(surface.contains("generated by ai"));
    }

    @Test
    void stripsTextBlocksSoRulesIgnoreTemplateProse() {
        String src = """
                class T {
                  String yaml() {
                    return \"""
                        forbidden_calls: ["Generated by AI"]
                        \""";
                  }
                }
                """;
        String surface = JavaDesignSurface.lowerForRuleMatching("X.java", src);
        assertFalse(surface.contains("generated by ai"));
    }
}
